<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\tests.props" />
  <PropertyGroup>
    <TargetFrameworks>net8.0</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\DataFilters.AspNetCore\DataFilters.AspNetCore.csproj" />
  </ItemGroup>

</Project>
