<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\core.props" />

  <PropertyGroup>
    <TargetFrameworks>netstandard2.1;net8.0</TargetFrameworks>
    <PackageTags>datafilters; filtering; filter; ifilter; </PackageTags>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DataFilters" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DataFilters.AspNetCore.Attributes\DataFilters.AspNetCore.Attributes.csproj" />
  </ItemGroup>

</Project>